server:
  port: ${PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASS}
    from: ${MAIL_USERNAME}
  application:
    name: lead-service



twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
  whatsapp-number: ${TWILIO_WHATSAPP_NUMBER}

  lead:
    creation_acknowledgement: ${template_lead_creation_acknowledgement}
    assignment_notification: ${template_lead_assignment_notification}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

sendgrid:
  api-key: ${SENDGRID_API_KEY}


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EurekaUrl}
  instance:
    prefer-ip-address: true


env:
  path: ${ENV_PATH}
